### PR TITLE
Add rubocop rules and fix failing checks

### PR DESCRIPTION
**Pull request by sarslanoglu**
Screen Shot 2020-04-27 at 11 42 15
Only ```app/controllers/api/hospitals_controller``` create method needs refactor to pass remaining failing checks. I can refactor method but any person from the maintainers would be much better since I can broke flow. Other than that here is my some preferences about rules.

- I prefer single quotes if there is no need for double [Double vs single quotes](https://stackoverflow.com/questions/6395288/double-vs-single-quotes)
- I prefer 100 chars max for line (default is 80) it is optimal to use it between 100 - 120. We can discuss if there is ambiguity

For other rules I follow the projects main flow and try to fix them. We can continue discussion in this pr. Stay home, stay safe.

### CODE REVIEW

**Comment by sarslanoglu** [comment]
@dimanyc @hantuzun Any suggestion or comment regarding to this issue?

**Comment by dimanyc** [comment]
How about disabling rubocop for that action for now and filing a separate issue to refactor the create method?

**Comment by sarslanoglu** [comment]
Currently all checks are passing. I just created an issue for refactoring hospitals_controller create method.
Screen Shot 2020-05-04 at 15 39 37

**Comment by sarslanoglu** [comment]
@dimanyc Is it good to merge?

**Comment by dimanyc** [comment]
I think so! @hantuzun wdut?

**Comment by sarslanoglu** [comment]
Closing due to inactivity

**Pull request closed without merging**
